### PR TITLE
chore: improve Windows support

### PR DESCRIPTION
**Pull request by ereslibre**
Bump the policy-fetcher that improves Windows path support on the
policy store.

### CODE REVIEW

**Review by flavio — APPROVED** [review]
LGTM, ofc the policy-fetcher version must changed to use the official repo

**Comment by ereslibre** [comment]
> ofc the policy-fetcher version must changed to use the official repo

Yes, when I include this in "main" repos is just to ease the review process. It's always to be put back as expected before merge.

**Review by flavio — APPROVED** [review]
LGTM

**Review by jvanz — APPROVED** [review]

**Review by viccuad — APPROVED** [review]

**Comment by ereslibre** [comment]
Merging on green and doing a new rc release.

**Pull request merged**
