### PR TITLE
fix: Ensure release assets have proper name

### PR DESCRIPTION
**Pull request by flavio**
The GH action uploading the release assets must provide the base name of the file, not its full path.

With kubewarden 1.7.0-rc2 we accidentally got all the release assets to contain the entire path to the file. For example, we had `default.kwctl-airgap-scripts.kubewarden-load-policies.sh` instead of
`kubewarden-load-policies.sh`.

### CODE REVIEW

**Review by viccuad — APPROVED** [review]
LGTM!

**Review by jvanz — APPROVED** [review]

**Comment by flavio** [comment]
I currently testing that into my fork, I'll merge it if everything works as expected

**Review by viccuad — APPROVED** [review]
LGTM!

Thanks Flavio for the move to cross, it indeed simplifies things. Plus thanks for the pinning of GHA repos, it's a lot of busywork.

**Comment by flavio** [comment]
Everything is ready to be merged. [This](https://github.com/flavio/kwctl/releases/tag/untagged-3fca3150d01715654ec9) is a test release on my fork. All the assets look fine.

**Pull request merged**
