### PR TITLE
Enable "get OCI manifest digest" callback

### PR DESCRIPTION
**Pull request by flavio**
Ensure the Kubewarden policies executed via kwctl can request the host to fetch the manifest digest of an OCI image.

Note well: the current code works, but I wonder what is the right place of the new `src/callback_handler` directory should be. This is code that is probably going to be shared with the policy-server as it currently is.
I need to do more thinking about that.

### CODE REVIEW

**Comment by flavio** [comment]
There are still some minor details to sort out, but this is now ready for review.

**Review by ereslibre — APPROVED** [review]
LGTM modulo lints

**Review by viccuad — APPROVED** [review]
LGTM. Maybe it can be a module in policy-evaluator?

**Comment by flavio** [comment]
> LGTM. Maybe it can be a module in policy-evaluator?

Yes, either a module or, even better, a crate that lives in there. What do you think folks?

**Comment by ereslibre** [comment]
> Yes, either a module or, even better, a crate that lives in there. What do you think folks?

I'm good with both. As we depend on policy-evaluator already so I would favor a module at this point, and create a crate out of it if we see the need.

**Comment by flavio** [comment]
This is now done via https://github.com/kubewarden/kwctl/issues/205

**Pull request closed without merging**
